#!/bin/bash
#cd Dropbox/GitHub/MTWABP/FunAndGames/PINBALL/MPF_GAMES_v57/BAM_6MDM_v57/
#cd Dropbox/GitHub/MTWABP/FunAndGames/PINBALL/MPF_GAMES_v57/BAM_BUCK_ROGERS_v57/
#cd Dropbox/GitHub/MTWABP/FunAndGames/PINBALL/MPF_GAMES_v57/BAM_CAPT_FANTASTIC_v57/
#cd Dropbox/GitHub/MTWABP/FunAndGames/PINBALL/MPF_GAMES_v57/BAM_CHARLIES_ANGELS_v57/
#cd Dropbox/GitHub/MTWABP/FunAndGames/PINBALL/MPF_GAMES_v57/BAM_EIGHT_BALL_v57/
#cd Dropbox/GitHub/MTWABP/FunAndGames/PINBALL/MPF_GAMES_v57/BAM_FLASH_GORDON_v57/
#cd Dropbox/GitHub/MTWABP/FunAndGames/PINBALL/MPF_GAMES_v57/BAM_GLOBETROTTERS_v57/
#cd Dropbox/GitHub/MTWABP/FunAndGames/PINBALL/MPF_GAMES_v57/BAM_HULK_v57/
#cd Dropbox/GitHub/MTWABP/FunAndGames/PINBALL/MPF_GAMES_v57/BAM_IRON_MAIDEN_v57/
#cd Dropbox/GitHub/MTWABP/FunAndGames/PINBALL/MPF_GAMES_v57/BAM_JAMES_BOND_v57/
#cd Dropbox/GitHub/MTWABP/FunAndGames/PINBALL/MPF_GAMES_v57/BAM_JUPITER_CRUSH_v57/
#cd Dropbox/GitHub/MTWABP/FunAndGames/PINBALL/MPF_GAMES_v57/BAM_KISS_v57/
#cd Dropbox/GitHub/MTWABP/FunAndGames/PINBALL/MPF_GAMES_v57/BAM_MATA_HARI_v57/
#cd Dropbox/GitHub/MTWABP/FunAndGames/PINBALL/MPF_GAMES_v57/BAM_MISS_ADVENTURE_v57/
#cd Dropbox/GitHub/MTWABP/FunAndGames/PINBALL/MPF_GAMES_v57/BAM_PLAYBOY_v57/
cd Dropbox/GitHub/MTWABP/FunAndGames/PINBALL/MPF_GAMES_v57/BAM_SILVERBALL_MANIA_v57/
#cd Dropbox/GitHub/MTWABP/FunAndGames/PINBALL/MPF_GAMES_v57/BAM_SPIDERMAN_v57/
#cd Dropbox/GitHub/MTWABP/FunAndGames/PINBALL/MPF_GAMES_v57/BAM_STAR_TREK_v57/
#cd Dropbox/GitHub/MTWABP/FunAndGames/PINBALL/MPF_GAMES_v57/BAM_STERN_ALI_v57/
#cd Dropbox/GitHub/MTWABP/FunAndGames/PINBALL/MPF_GAMES_v57/BAM_STERN_MAGIC_v57/
#cd Dropbox/GitHub/MTWABP/FunAndGames/PINBALL/MPF_GAMES_v57/BAM_STRIKES_SPARES_v57/
#cd Dropbox/GitHub/MTWABP/FunAndGames/PINBALL/MPF_GAMES_v57/BAM_SUPERMAN_v57/
#cd Dropbox/GitHub/MTWABP/FunAndGames/PINBALL/MPF_GAMES_v57/BAM_TATTOO_MYSTIQUE_v57/
#cd Dropbox/GitHub/MTWABP/FunAndGames/PINBALL/MPF_GAMES_v57/BAM_TEST_v57/
#cd Dropbox/GitHub/MTWABP/FunAndGames/PINBALL/MPF_GAMES_v57/BAM_TOTEM_v57/
#cd Dropbox/GitHub/MTWABP/FunAndGames/PINBALL/MPF_GAMES_v57/BAM_VIKING_v57/
#cd Dropbox/GitHub/MTWABP/FunAndGames/PINBALL/MPF_GAMES_v57/BAM_VOLTAN_v57/

sleep 2s
mpf both -xvVaA
#mpf both -vVaA
#mpf both